- purl: pkg:rpm/redhat/ansible@2.2.1.0-2.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0260
    - redhat_importer_v2/RHSA-2017:0448
    - redhat_importer_v2/RHSA-2017:1367
- purl: pkg:rpm/redhat/ansible@2.2.1.0-2.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0260
    - redhat_importer_v2/RHSA-2017:0448
    - redhat_importer_v2/RHSA-2017:1367
