- purl: pkg:deb/debian/kubernetes@0?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2015-5305
    - debian_importer_v2/kubernetes/CVE-2015-7528
    - debian_importer_v2/kubernetes/CVE-2016-1905
    - debian_importer_v2/kubernetes/CVE-2016-1906
    - debian_importer_v2/kubernetes/CVE-2017-1002100
    - debian_importer_v2/kubernetes/CVE-2018-1002101
    - debian_importer_v2/kubernetes/CVE-2019-1002101
    - debian_importer_v2/kubernetes/CVE-2019-11243
    - debian_importer_v2/kubernetes/CVE-2019-11244
    - debian_importer_v2/kubernetes/CVE-2019-11245
    - debian_importer_v2/kubernetes/CVE-2019-11246
    - debian_importer_v2/kubernetes/CVE-2019-11249
    - debian_importer_v2/kubernetes/CVE-2019-11251
    - debian_importer_v2/kubernetes/CVE-2020-8554
    - debian_importer_v2/kubernetes/CVE-2020-8563
    - debian_importer_v2/kubernetes/CVE-2021-25736
    - debian_importer_v2/kubernetes/CVE-2021-25749
    - debian_importer_v2/kubernetes/CVE-2023-5528
    - debian_importer_v2/kubernetes/CVE-2024-5321
    - debian_importer_v2/kubernetes/CVE-2024-9042
