- purl: pkg:deb/ubuntu/cloud-init@19.4-56-g06e324ff-0ubuntu1?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8632
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
