- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
- purl: pkg:rpm/redhat/cloud-init@18.2-1.el7_6.2?arch=ppc64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0597
