- purl: pkg:rpm/redhat/ansible@2.7.8-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0430
    - redhat_importer_v2/RHSA-2019:0431
- purl: pkg:rpm/redhat/ansible@2.7.8-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0430
    - redhat_importer_v2/RHSA-2019:0431
