- purl: pkg:maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6@0.18.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-c4r9-r8fh-9vj2
    - gitlab_importer_v2/maven/io.prometheus.jmx/jmx_prometheus_httpserver_java6/CVE-2022-38749
  fixing_advisories: []
