- purl: pkg:rpm/redhat/prometheus@3.11.374-1.git.5026.29379c4.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0079
- purl: pkg:rpm/redhat/prometheus@3.11.374-1.git.5026.29379c4.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0079
