- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.11
  affected_by_advisories: []
  fixing_advisories:
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2018-1999040
