- purl: pkg:gem/dependabot-omnibus@0.125.1
  affected_by_advisories:
    - gitlab_importer_v2/gem/dependabot-omnibus/CVE-2020-26222
    - ruby_importer_v2/gems/dependabot-omnibus/CVE-2020-26222
  fixing_advisories:
    - github_osv_importer_v2/GHSA-23f7-99jx-m54r
    - ruby_importer_v2/gems/dependabot-omnibus/CVE-2020-26222
