- purl: pkg:deb/debian/ansible@2.8.6%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2019-10206
    - debian_importer_v2/ansible/CVE-2019-10217
    - debian_importer_v2/ansible/CVE-2019-14846
    - debian_importer_v2/ansible/CVE-2019-14858
