- purl: pkg:rpm/redhat/golang-github-prometheus-alertmanager@0.14.0-1.git30af4d0.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:0489
    - redhat_importer_v2/RHBA-2018:1816
