- purl: pkg:pypi/esphome@1.18.0b3
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-48mj-p7x2-5jfm
    - github_osv_importer_v2/GHSA-mxh2-ccgj-8635
    - gitlab_importer_v2/pypi/esphome/CVE-2021-41104
    - gitlab_importer_v2/pypi/esphome/CVE-2025-57808
    - pypa_importer_v2/PYSEC-2021-351
    - pysec_importer_v2/PYSEC-2021-351
  fixing_advisories: []
