- purl: pkg:deb/debian/cloud-init@25.1.4-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/cloud-init/CVE-2024-11584
    - debian_importer_v2/cloud-init/CVE-2024-6174
