- purl: pkg:pypi/ansible@2.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-h653-95qw-h2mp
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10874
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10875
    - gitlab_importer_v2/pypi/ansible/CVE-2018-16837
    - gitlab_importer_v2/pypi/ansible/CVE-2018-7750
    - gitlab_importer_v2/pypi/ansible/CVE-2019-14846
    - gitlab_importer_v2/pypi/ansible/CVE-2019-14858
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20228
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3533
  fixing_advisories: []
