- purl: pkg:gem/dependabot-common@0.123.1
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-23f7-99jx-m54r
    - gitlab_importer_v2/gem/dependabot-common/CVE-2020-26222
    - ruby_importer_v2/gems/dependabot-common/CVE-2020-26222
  fixing_advisories: []
