- purl: pkg:rpm/redhat/ansible@2.8.4-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2542
    - redhat_importer_v2/RHSA-2019:2543
- purl: pkg:rpm/redhat/ansible@2.8.4-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2542
    - redhat_importer_v2/RHSA-2019:2543
