- purl: pkg:rpm/redhat/grafana@5.2.4-5.el7rhgs?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:1628
- purl: pkg:rpm/redhat/grafana@5.2.4-5.el7rhgs?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:1628
