- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-16.gitd5383c5.el9?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:4616
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-16.gitd5383c5.el9?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:4616
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-16.gitd5383c5.el9?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:4616
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-16.gitd5383c5.el9?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:4616
