- purl: pkg:pypi/ansible@2.9.18
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-4r65-35qq-ch8j
    - github_osv_importer_v2/GHSA-785x-qw4v-6872
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-f556-49jc-4rvc
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - github_osv_importer_v2/GHSA-x7jh-595q-wq82
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1736
    - gitlab_importer_v2/pypi/ansible/CVE-2020-25635
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20228
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3583
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3620
    - gitlab_importer_v2/pypi/ansible/CVE-2022-3697
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5115
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5764
    - gitlab_importer_v2/pypi/ansible/CVE-2025-14010
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2020-3
    - pypa_importer_v2/PYSEC-2021-1
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pypa_importer_v2/PYSEC-2021-358
    - pypa_importer_v2/PYSEC-2022-164
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2021-1
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2021-358
    - pysec_importer_v2/PYSEC-2022-164
  fixing_advisories:
    - github_osv_importer_v2/GHSA-fh5v-5f35-2rv2
    - github_osv_importer_v2/GHSA-wv5p-gmmv-wh9v
    - gitlab_importer_v2/pypi/ansible/CVE-2020-20178
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20178
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20180
    - pypa_importer_v2/PYSEC-2021-106
    - pypa_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-106
    - pysec_importer_v2/PYSEC-2021-124
