- purl: pkg:deb/ubuntu/cloud-init@19.3-41-gc4735dd3-0ubuntu1?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8632
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
- purl: pkg:deb/ubuntu/cloud-init@19.3-41-gc4735dd3-0ubuntu1?arch=source&distro=esm-infra/focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5536
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11584
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
  fixing_advisories: []
