- purl: pkg:rpm/redhat/cloud-init@18.5-1.el8.4?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:1992
- purl: pkg:rpm/redhat/cloud-init@18.5-1.el8.4?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:1992
