- purl: pkg:rpm/redhat/cloud-init@22.1-10.el9_2.1?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10879
- purl: pkg:rpm/redhat/cloud-init@22.1-10.el9_2.1?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10879
