- purl: pkg:rpm/redhat/cloud-init@24.4-3.el10_0.2?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10844
- purl: pkg:rpm/redhat/cloud-init@24.4-3.el10_0.2?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10844
