- purl: pkg:rpm/redhat/grafana@7.5.15-8.el8_8?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2026:0245
- purl: pkg:rpm/redhat/grafana@7.5.15-8.el8_8?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2026:0245
- purl: pkg:rpm/redhat/grafana@7.5.15-8.el8_8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2026:0245
