- purl: pkg:deb/debian/ansible@2.9.7%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2020-10684
    - debian_importer_v2/ansible/CVE-2020-10685
    - debian_importer_v2/ansible/CVE-2020-10691
    - debian_importer_v2/ansible/CVE-2020-1733
    - debian_importer_v2/ansible/CVE-2020-1735
    - debian_importer_v2/ansible/CVE-2020-1737
    - debian_importer_v2/ansible/CVE-2020-1739
    - debian_importer_v2/ansible/CVE-2020-1740
    - debian_importer_v2/ansible/CVE-2020-1746
