- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-36.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:2863
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.7.2-36.el8?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:2863
