- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.51-1.git.1063.12dd8be.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3743
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.51-1.git.1063.12dd8be.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3743
