- purl: pkg:rpm/redhat/docker@1.13.1-210.git7d71120.el7_9?arch=ppc64le&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1270
- purl: pkg:rpm/redhat/docker@1.13.1-210.git7d71120.el7_9?arch=s390x&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1270
- purl: pkg:rpm/redhat/docker@1.13.1-210.git7d71120.el7_9?arch=x86_64&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1270
- purl: pkg:rpm/redhat/docker@1.13.1-210.git7d71120.el7_9?arch=src&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1270
