- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.1
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-fqg2-c97r-rqcj
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2018-1999040
  fixing_advisories: []
