- purl: pkg:pypi/ansible@4.10.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5115
    - gitlab_importer_v2/pypi/ansible/CVE-2025-14010
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2021-125
  fixing_advisories: []
