- purl: pkg:npm/%40mittwald/kubernetes@3.5.0
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-g35x-j6jj-8g7j
    - gitlab_importer_v2/npm/@mittwald/kubernetes/GMS-2023-1356
