- purl: pkg:deb/debian/kubernetes@1.17.4-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2018-1002100
    - debian_importer_v2/kubernetes/CVE-2018-1002102
    - debian_importer_v2/kubernetes/CVE-2018-1002105
    - debian_importer_v2/kubernetes/CVE-2019-1002100
    - debian_importer_v2/kubernetes/CVE-2019-11247
    - debian_importer_v2/kubernetes/CVE-2019-11248
    - debian_importer_v2/kubernetes/CVE-2019-11250
    - debian_importer_v2/kubernetes/CVE-2019-11253
    - debian_importer_v2/kubernetes/CVE-2019-11254
    - debian_importer_v2/kubernetes/CVE-2019-9946
    - debian_importer_v2/kubernetes/CVE-2020-8551
    - debian_importer_v2/kubernetes/CVE-2020-8552
