- purl: pkg:rpm/redhat/helm@3.3.4-2.el8at?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:2703
- purl: pkg:rpm/redhat/helm@3.3.4-2.el8at?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:2703
