- purl: pkg:deb/debian/ansible@2.9.13%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2020-10744
    - debian_importer_v2/ansible/CVE-2020-14330
    - debian_importer_v2/ansible/CVE-2020-14332
    - debian_importer_v2/ansible/CVE-2020-14365
