- purl: pkg:rpm/redhat/ansible@2.8.11-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:1543
- purl: pkg:rpm/redhat/ansible@2.8.11-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:1543
