- purl: pkg:rpm/redhat/docker@1.6.2-14.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2015:1167
- purl: pkg:rpm/redhat/docker@1.6.2-14.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2015:1167
