- purl: pkg:maven/org.jenkins-ci.plugins/ansible@1.1
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-6xqj-wvgp-rqp8
    - gitlab_importer_v2/maven/org.jenkins-ci.plugins/ansible/CVE-2020-2310
