- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.248-1.git.1.66abd18.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:2990
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.248-1.git.1.66abd18.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:2990
