- purl: pkg:deb/ubuntu/prometheus-alertmanager@0.23.0-4ubuntu0.2%2Besm1?arch=source&distro=esm-apps/jammy
  affected_by_advisories: []
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-40577
