- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0-1.git85ceabc.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:3188
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0-1.git85ceabc.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:3188
