- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-14.el8?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3369
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-14.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3369
