- purl: pkg:deb/debian/kubernetes@1.18.5-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2020-8557
    - debian_importer_v2/kubernetes/CVE-2020-8558
    - debian_importer_v2/kubernetes/CVE-2020-8559
