- purl: pkg:deb/debian/prometheus@2.42.0%2Bds-5?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/prometheus/CVE-2019-3826
    - debian_importer_v2/prometheus/CVE-2021-29622
