- purl: pkg:deb/ubuntu/cloud-init@22.1-1-gb3d9acdd-0ubuntu1~22.04.1?arch=source&distro=jammy
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5536
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11584
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
  fixing_advisories: []
