- purl: pkg:maven/org.jenkins-ci.plugins/deploy@1.12
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-3q6p-r6rr-266x
    - gitlab_importer_v2/maven/org.jenkins-ci.plugins/deploy/CVE-2017-1000113
  fixing_advisories: []
