- purl: pkg:rpm/redhat/grafana@6.3.6-6.el8_2?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:8507
- purl: pkg:rpm/redhat/grafana@6.3.6-6.el8_2?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:8507
