- purl: pkg:deb/debian/ansible@5.4.0-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2021-3583
    - debian_importer_v2/ansible/CVE-2021-3620
    - debian_importer_v2/ansible/CVE-2023-5115
    - debian_importer_v2/ansible/CVE-2023-5764
    - debian_importer_v2/ansible/CVE-2024-0690
    - debian_importer_v2/ansible/CVE-2024-11079
    - debian_importer_v2/ansible/CVE-2024-8775
    - debian_importer_v2/ansible/CVE-2024-9902
