- purl: pkg:pypi/ansible@12.0.0b1
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - gitlab_importer_v2/pypi/ansible/CVE-2025-14010
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2021-125
  fixing_advisories: []
