- purl: pkg:rpm/redhat/python3-ironic-prometheus-exporter@4.3.0-0.20231219134422.5211827.el9?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:0045
    - redhat_importer_v2/RHSA-2024:3722
