- purl: pkg:rpm/redhat/ansible@2.9.27-1.el8ap?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3874
- purl: pkg:rpm/redhat/ansible@2.9.27-1.el8ap?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3874
