- purl: pkg:rpm/redhat/ansible@2.7.5-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3837
    - redhat_importer_v2/RHSA-2018:3838
- purl: pkg:rpm/redhat/ansible@2.7.5-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3837
    - redhat_importer_v2/RHSA-2018:3838
