- purl: pkg:deb/ubuntu/cloud-init@21.2-3-g899bfaa9-0ubuntu2~18.04.1?arch=source&distro=bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
