- purl: pkg:rpm/redhat/ansible@2.6.1-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2151
    - redhat_importer_v2/RHSA-2018:2166
- purl: pkg:rpm/redhat/ansible@2.6.1-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2151
    - redhat_importer_v2/RHSA-2018:2166
