- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@3910.ve59cec5e33ea
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-v5hq-cqqr-6w4g
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2023-30513
