- purl: pkg:rpm/redhat/ansible@2.9.4-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:0215
    - redhat_importer_v2/RHSA-2020:0218
- purl: pkg:rpm/redhat/ansible@2.9.4-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:0215
    - redhat_importer_v2/RHSA-2020:0218
