- purl: pkg:npm/json-ptr@1.3.2-dependabot-npm-and-yarn-lodash-4-17-19.7fd4b3e
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-8gwj-8hxc-285w
    - github_osv_importer_v2/GHSA-rrqv-vjrw-hrcr
    - github_osv_importer_v2/GHSA-x5r6-x823-9848
  fixing_advisories: []
