- purl: pkg:rpm/redhat/cloud-init@23.1.1-11.el9?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6371
- purl: pkg:rpm/redhat/cloud-init@23.1.1-11.el9?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6371
