- purl: pkg:maven/org.jenkins-ci.plugins/ansible@0.8
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-322x-jv5h-cvjh
    - gitlab_importer_v2/maven/org.jenkins-ci.plugins/ansible/CVE-2018-1000149
  fixing_advisories: []
