- purl: pkg:deb/ubuntu/prometheus@0.14.0%2Bds-1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-29622
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_advisories: []
