- purl: pkg:deb/ubuntu/grafana@2.6.0%2Bdfsg-1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-1000816
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-12099
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-15727
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18623
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18624
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-18625
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-19039
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-15043
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-15635
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-19499
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-11110
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-12052
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-12245
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-12458
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-13430
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-24303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-27358
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-39226
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-41174
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-41244
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-43798
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-43813
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-43815
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21673
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21702
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21703
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21713
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-23498
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-26148
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-31097
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-31107
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-31123
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-31130
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-35957
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-36062
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39201
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39229
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39306
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39307
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39324
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-39328
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-0507
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-0594
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1387
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1410
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2183
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-22462
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2801
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3128
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4822
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-6152
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-10452
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11741
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-1313
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-1442
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6322
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-8118
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9264
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9476
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-1088
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-3260
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-3415
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-3454
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-3580
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-41117
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-41117
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-4123
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-6023
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-6197
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2026-21720
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2026-21721
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2026-21722
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2026-21725
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2026-21727
  fixing_advisories: []
