- purl: pkg:pypi/ansible@2.9.0a1
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-3c67-gc48-983w
    - github_osv_importer_v2/GHSA-3m93-m4q6-mc6v
    - github_osv_importer_v2/GHSA-5rrg-rr89-x9mv
    - github_osv_importer_v2/GHSA-77g3-3j5w-64w4
    - github_osv_importer_v2/GHSA-86hp-cj9j-33vv
    - github_osv_importer_v2/GHSA-893h-35v4-mxqx
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-923p-fr2c-g5m2
    - github_osv_importer_v2/GHSA-f85h-23mf-2fwh
    - github_osv_importer_v2/GHSA-frxj-5j27-f8rf
    - github_osv_importer_v2/GHSA-g4mq-6fp5-qwcf
    - github_osv_importer_v2/GHSA-gfr2-qpxh-qj9m
    - github_osv_importer_v2/GHSA-gwr8-5j83-483c
    - github_osv_importer_v2/GHSA-h39q-95q5-9jfp
    - github_osv_importer_v2/GHSA-h653-95qw-h2mp
    - github_osv_importer_v2/GHSA-j2h6-73x8-22c4
    - github_osv_importer_v2/GHSA-j667-c2hm-f2wp
    - github_osv_importer_v2/GHSA-m429-fhmv-c6q2
    - github_osv_importer_v2/GHSA-p62g-jhg6-v3rq
    - github_osv_importer_v2/GHSA-vcg8-98q8-g7mj
    - gitlab_importer_v2/pypi/ansible/CVE-2019-14858
    - gitlab_importer_v2/pypi/ansible/CVE-2019-14905
    - gitlab_importer_v2/pypi/ansible/CVE-2020-10684
    - gitlab_importer_v2/pypi/ansible/CVE-2020-14365
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1733
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1734
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1746
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20191
  fixing_advisories: []
