- purl: pkg:rpm/redhat/prometheus-promu@0.5.0-3.git642a960.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0713
- purl: pkg:rpm/redhat/prometheus-promu@0.5.0-3.git642a960.el7?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0713
- purl: pkg:rpm/redhat/prometheus-promu@0.5.0-3.git642a960.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0713
