- purl: pkg:rpm/redhat/grafana@6.3.6-7.el8_2?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:8684
- purl: pkg:rpm/redhat/grafana@6.3.6-7.el8_2?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:8684
