- purl: pkg:rpm/redhat/grafana@7.5.11-4.el8_6?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:5864
- purl: pkg:rpm/redhat/grafana@7.5.11-4.el8_6?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:5864
- purl: pkg:rpm/redhat/grafana@7.5.11-4.el8_6?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:5864
- purl: pkg:rpm/redhat/grafana@7.5.11-4.el8_6?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:5864
- purl: pkg:rpm/redhat/grafana@7.5.11-4.el8_6?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:5864
