- purl: pkg:rpm/redhat/ansible@2.2.3.0-1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2017:1716
    - redhat_importer_v2/RHSA-2017:1244
    - redhat_importer_v2/RHSA-2017:1334
    - redhat_importer_v2/RHSA-2017:1476
    - redhat_importer_v2/RHSA-2017:1499
    - redhat_importer_v2/RHSA-2017:1599
- purl: pkg:rpm/redhat/ansible@2.2.3.0-1.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2017:1716
    - redhat_importer_v2/RHSA-2017:1244
    - redhat_importer_v2/RHSA-2017:1334
    - redhat_importer_v2/RHSA-2017:1476
    - redhat_importer_v2/RHSA-2017:1499
    - redhat_importer_v2/RHSA-2017:1599
