- purl: pkg:rpm/redhat/cloud-init@18.5-7.el8_1.6?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3177
- purl: pkg:rpm/redhat/cloud-init@18.5-7.el8_1.6?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3177
