- purl: pkg:rpm/redhat/golang-github-prometheus-prometheus@2.2.1-1.gitbc6058c.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:1566
    - redhat_importer_v2/RHBA-2018:1816
