- purl: pkg:deb/ubuntu/cloud-init@24.1~5g1f6eddd5-0ubuntu1?arch=source&distro=noble
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11584
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
  fixing_advisories: []
