- purl: pkg:deb/debian/prometheus-alertmanager@0.25.0-1?distro=trixie
  affected_by_advisories:
    - debian_importer_v2/prometheus-alertmanager/CVE-2023-40577
    - debian_importer_v2/prometheus-alertmanager/CVE-2023-40577
    - debian_importer_v2/prometheus-alertmanager/CVE-2023-40577
  fixing_advisories: []
