- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.21.1-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/golang-github-prometheus-client-golang/CVE-2022-21698
