- purl: pkg:rpm/redhat/ansible@2.9.18-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0663
    - redhat_importer_v2/RHSA-2021:0664
    - redhat_importer_v2/RHSA-2021:2180
- purl: pkg:rpm/redhat/ansible@2.9.18-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0663
    - redhat_importer_v2/RHSA-2021:0664
    - redhat_importer_v2/RHSA-2021:2180
