- purl: pkg:deb/ubuntu/cloud-init@0.7.8-49-g9e904bb-0ubuntu1~16.04.4?arch=source&distro=esm-infra/xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8631
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8632
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5536
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
  fixing_advisories: []
- purl: pkg:deb/ubuntu/cloud-init@0.7.8-49-g9e904bb-0ubuntu1~16.04.4?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
  fixing_advisories: []
