- purl: pkg:rpm/redhat/docker@1.9.1-40.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2016:1034
- purl: pkg:rpm/redhat/docker@1.9.1-40.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2016:1034
