- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.27.3
  affected_by_advisories:
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2020-2307
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2020-2308
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2020-2309
  fixing_advisories: []
