- purl: pkg:pypi/ansible@2.4
  affected_by_advisories:
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10874
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10875
    - gitlab_importer_v2/pypi/ansible/CVE-2018-7750
  fixing_advisories: []
