- purl: pkg:deb/debian/ansible@2.9.4%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2019-14904
    - debian_importer_v2/ansible/CVE-2019-14905
