- purl: pkg:deb/ubuntu/cloud-init@20.2-45-g5f7825e2-0ubuntu1~20.04.1?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
