- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.462-1.git.13de638.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:2517
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.462-1.git.13de638.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:2517
