- purl: pkg:rpm/redhat/ansible@2.8.6-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3203
    - redhat_importer_v2/RHSA-2019:3207
- purl: pkg:rpm/redhat/ansible@2.8.6-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3203
    - redhat_importer_v2/RHSA-2019:3207
