- purl: pkg:rpm/redhat/ansible@2.2.0.0-1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2016:2778
- purl: pkg:rpm/redhat/ansible@2.2.0.0-1.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2016:2778
