- purl: pkg:npm/%40mittwald/kubernetes@1.0.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-g35x-j6jj-8g7j
    - gitlab_importer_v2/npm/@mittwald/kubernetes/GMS-2023-1356
  fixing_advisories: []
