- purl: pkg:rpm/redhat/tfm-rubygem-prometheus-client@0.7.1-1.el7sat?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2927
- purl: pkg:rpm/redhat/tfm-rubygem-prometheus-client@0.7.1-1.el7sat?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2927
