- purl: pkg:rpm/redhat/ansible@2.9.27-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3871
    - redhat_importer_v2/RHSA-2021:3872
    - redhat_importer_v2/RHSA-2021:4703
- purl: pkg:rpm/redhat/ansible@2.9.27-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3871
    - redhat_importer_v2/RHSA-2021:3872
    - redhat_importer_v2/RHSA-2021:4703
