- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=armhf&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=x86&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=x86_64&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=aarch64&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=armv7&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=ppc64le&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
- purl: pkg:apk/alpine/ansible@2.8.9-r0?arch=s390x&distroversion=v3.10&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1737
    - alpine_linux_importer_v2/ansible/v3.10/2.8.9-r0/CVE-2020-1739
