- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=s390x&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=x86&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=x86_64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=ppc64le&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=aarch64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=armhf&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
- purl: pkg:apk/alpine/docker@25.0.5-r0?arch=armv7&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/25.0.5-r0/CVE-2024-29018
