- purl: pkg:deb/ubuntu/cloud-init@17.2-35-gf576b2a2-0ubuntu1~16.04.2?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-0816
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
  fixing_advisories: []
