- purl: pkg:pypi/ansible@2.10.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-5rrg-rr89-x9mv
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-f556-49jc-4rvc
    - github_osv_importer_v2/GHSA-j667-c2hm-f2wp
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - github_osv_importer_v2/GHSA-x7jh-595q-wq82
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1736
    - gitlab_importer_v2/pypi/ansible/CVE-2020-25635
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20191
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5115
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5764
    - gitlab_importer_v2/pypi/ansible/CVE-2025-14010
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
  fixing_advisories:
    - github_osv_importer_v2/GHSA-785x-qw4v-6872
    - gitlab_importer_v2/pypi/ansible/CVE-2022-3697
    - pypa_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2020-3
