- purl: pkg:rpm/redhat/ansible@2.3.1.0-3.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:2524
- purl: pkg:rpm/redhat/ansible@2.3.1.0-3.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:2524
