- purl: pkg:rpm/redhat/cloud-init@24.4-4.el9_6.3?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10848
- purl: pkg:rpm/redhat/cloud-init@24.4-4.el9_6.3?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10848
