- purl: pkg:rpm/redhat/prometheus@3.11.420-1.git.5026.1e8cb9c.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
- purl: pkg:rpm/redhat/prometheus@3.11.420-1.git.5026.1e8cb9c.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
