- purl: pkg:deb/ubuntu/prometheus-blackbox-exporter@0.24.0-1build1
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-16248
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-26735
  fixing_advisories: []
