- purl: pkg:rpm/redhat/ansible@2.9.6-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:0784
- purl: pkg:rpm/redhat/ansible@2.9.6-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:0784
