- purl: pkg:deb/ubuntu/prometheus@1.8.1%2Bds-2?arch=source&distro=bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-3826
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-46146
  fixing_advisories: []
