- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=armhf&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=s390x&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=ppc64le&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=x86_64&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=x86&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
- purl: pkg:apk/alpine/ansible@2.4.6.0-r1?arch=aarch64&distroversion=v3.7&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.7/2.4.6.0-r1/CVE-2019-10206
