- purl: pkg:deb/debian/netplan.io@0.101-4?distro=trixie
  affected_by_advisories:
    - debian_importer_v2/netplan.io/CVE-2022-4968
    - debian_importer_v2/netplan.io/CVE-2022-4968
    - debian_importer_v2/netplan.io/CVE-2022-4968
  fixing_advisories: []
