- purl: pkg:pypi/ansible@2.6
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-3xvg-x47j-x75w
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10874
    - gitlab_importer_v2/pypi/ansible/CVE-2018-10875
  fixing_advisories: []
