- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-2.gitceca8c1.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:0489
    - redhat_importer_v2/RHBA-2018:1816
    - redhat_importer_v2/RHBA-2018:2652
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-2.gitceca8c1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:0489
    - redhat_importer_v2/RHBA-2018:1816
    - redhat_importer_v2/RHBA-2018:2652
