- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=armhf&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=s390x&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=ppc64le&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=aarch64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=mips64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=armv7&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=x86_64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@20.4.1-r1?arch=x86&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.13/20.4.1-r1/CVE-2021-3429
