- purl: pkg:rpm/redhat/grafana@10.2.6-17.el9_7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23087
- purl: pkg:rpm/redhat/grafana@10.2.6-17.el9_7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23087
- purl: pkg:rpm/redhat/grafana@10.2.6-17.el9_7?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23087
- purl: pkg:rpm/redhat/grafana@10.2.6-17.el9_7?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23087
- purl: pkg:rpm/redhat/grafana@10.2.6-17.el9_7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23087
