- purl: pkg:apk/alpine/ansible@2.1.4.0-r0?arch=armhf&distroversion=v3.4&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.4/2.1.4.0-r0/CVE-2016-9587
- purl: pkg:apk/alpine/ansible@2.1.4.0-r0?arch=x86&distroversion=v3.4&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.4/2.1.4.0-r0/CVE-2016-9587
- purl: pkg:apk/alpine/ansible@2.1.4.0-r0?arch=x86_64&distroversion=v3.4&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.4/2.1.4.0-r0/CVE-2016-9587
