- purl: pkg:rpm/redhat/docker@1.4.1-37.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2015:0623
- purl: pkg:rpm/redhat/docker@1.4.1-37.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2015:0623
