- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.10.0
  affected_by_advisories:
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2021-21661
  fixing_advisories: []
