- purl: pkg:npm/docker-compose-remote-api@0.1.4
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-q6pj-jh94-5fpr
    - gitlab_importer_v2/npm/docker-compose-remote-api/CVE-2020-7606
  fixing_advisories: []
