- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-8.el8_6?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6820
- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-8.el8_6?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6820
