- purl: pkg:deb/debian/ansible@0?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2013-4260
    - debian_importer_v2/ansible/CVE-2018-16859
    - debian_importer_v2/ansible/CVE-2019-14856
    - debian_importer_v2/ansible/CVE-2020-25635
    - debian_importer_v2/ansible/CVE-2020-25636
    - debian_importer_v2/ansible/CVE-2020-25646
    - debian_importer_v2/ansible/CVE-2025-14010
