- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=x86_64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=x86&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=s390x&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=ppc64le&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=armv7&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=armhf&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
- purl: pkg:apk/alpine/docker@20.10.24-r0?arch=aarch64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28840
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28841
    - alpine_linux_importer_v2/docker/v3.17/20.10.24-r0/CVE-2023-28842
