- purl: pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?distro=trixie
  affected_by_advisories:
    - debian_importer_v2/cloud-init/CVE-2023-1786
    - debian_importer_v2/cloud-init/CVE-2023-1786
    - debian_importer_v2/cloud-init/CVE-2023-1786
    - debian_importer_v2/cloud-init/CVE-2024-11584
    - debian_importer_v2/cloud-init/CVE-2024-11584
    - debian_importer_v2/cloud-init/CVE-2024-11584
    - debian_importer_v2/cloud-init/CVE-2024-11584
    - debian_importer_v2/cloud-init/CVE-2024-6174
    - debian_importer_v2/cloud-init/CVE-2024-6174
    - debian_importer_v2/cloud-init/CVE-2024-6174
    - debian_importer_v2/cloud-init/CVE-2024-6174
  fixing_advisories:
    - debian_importer_v2/cloud-init/CVE-2012-6639
    - debian_importer_v2/cloud-init/CVE-2019-0816
    - debian_importer_v2/cloud-init/CVE-2020-8631
    - debian_importer_v2/cloud-init/CVE-2020-8632
    - debian_importer_v2/cloud-init/CVE-2021-3429
    - debian_importer_v2/cloud-init/CVE-2022-2084
