- purl: pkg:gem/dependabot-omnibus@0.125.2
  affected_by_advisories:
    - ruby_importer_v2/gems/dependabot-omnibus/CVE-2020-26222
  fixing_advisories:
    - gitlab_importer_v2/gem/dependabot-omnibus/CVE-2020-26222
