- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.153-1.git.1.2768abd.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:3139
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.153-1.git.1.2768abd.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:3139
