- purl: pkg:pypi/ansible@2.7.6
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-3m93-m4q6-mc6v
    - github_osv_importer_v2/GHSA-4r65-35qq-ch8j
    - github_osv_importer_v2/GHSA-5rrg-rr89-x9mv
    - github_osv_importer_v2/GHSA-6fq2-x65v-v9h7
    - github_osv_importer_v2/GHSA-74vq-h4q8-x6jv
    - github_osv_importer_v2/GHSA-77g3-3j5w-64w4
    - github_osv_importer_v2/GHSA-785x-qw4v-6872
    - github_osv_importer_v2/GHSA-86hp-cj9j-33vv
    - github_osv_importer_v2/GHSA-893h-35v4-mxqx
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-923p-fr2c-g5m2
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-cqmr-rcpr-cxh3
    - github_osv_importer_v2/GHSA-f556-49jc-4rvc
    - github_osv_importer_v2/GHSA-f85h-23mf-2fwh
    - github_osv_importer_v2/GHSA-frxj-5j27-f8rf
    - github_osv_importer_v2/GHSA-g4mq-6fp5-qwcf
    - github_osv_importer_v2/GHSA-gfr2-qpxh-qj9m
    - github_osv_importer_v2/GHSA-grgm-pph5-j5h7
    - github_osv_importer_v2/GHSA-gwr8-5j83-483c
    - github_osv_importer_v2/GHSA-h39q-95q5-9jfp
    - github_osv_importer_v2/GHSA-h653-95qw-h2mp
    - github_osv_importer_v2/GHSA-j2h6-73x8-22c4
    - github_osv_importer_v2/GHSA-j667-c2hm-f2wp
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - github_osv_importer_v2/GHSA-p62g-jhg6-v3rq
    - github_osv_importer_v2/GHSA-pm48-cvv2-29q5
    - github_osv_importer_v2/GHSA-r6h7-5pq2-j77h
    - github_osv_importer_v2/GHSA-vcg8-98q8-g7mj
    - github_osv_importer_v2/GHSA-vp9j-rghq-8jhh
    - github_osv_importer_v2/GHSA-wv5p-gmmv-wh9v
    - github_osv_importer_v2/GHSA-x7jh-595q-wq82
    - pypa_importer_v2/PYSEC-2018-60
    - pypa_importer_v2/PYSEC-2019-145
    - pypa_importer_v2/PYSEC-2019-146
    - pypa_importer_v2/PYSEC-2019-171
    - pypa_importer_v2/PYSEC-2019-2
    - pypa_importer_v2/PYSEC-2019-4
    - pypa_importer_v2/PYSEC-2019-5
    - pypa_importer_v2/PYSEC-2020-1
    - pypa_importer_v2/PYSEC-2020-10
    - pypa_importer_v2/PYSEC-2020-11
    - pypa_importer_v2/PYSEC-2020-12
    - pypa_importer_v2/PYSEC-2020-13
    - pypa_importer_v2/PYSEC-2020-160
    - pypa_importer_v2/PYSEC-2020-161
    - pypa_importer_v2/PYSEC-2020-206
    - pypa_importer_v2/PYSEC-2020-207
    - pypa_importer_v2/PYSEC-2020-208
    - pypa_importer_v2/PYSEC-2020-210
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2020-3
    - pypa_importer_v2/PYSEC-2020-5
    - pypa_importer_v2/PYSEC-2020-6
    - pypa_importer_v2/PYSEC-2020-7
    - pypa_importer_v2/PYSEC-2020-8
    - pypa_importer_v2/PYSEC-2020-9
    - pypa_importer_v2/PYSEC-2021-1
    - pypa_importer_v2/PYSEC-2021-105
    - pypa_importer_v2/PYSEC-2021-106
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pypa_importer_v2/PYSEC-2021-358
    - pypa_importer_v2/PYSEC-2022-164
    - pysec_importer_v2/PYSEC-2018-60
    - pysec_importer_v2/PYSEC-2019-145
    - pysec_importer_v2/PYSEC-2019-146
    - pysec_importer_v2/PYSEC-2019-171
    - pysec_importer_v2/PYSEC-2019-2
    - pysec_importer_v2/PYSEC-2019-4
    - pysec_importer_v2/PYSEC-2019-5
    - pysec_importer_v2/PYSEC-2019-72
    - pysec_importer_v2/PYSEC-2019-74
    - pysec_importer_v2/PYSEC-2019-75
    - pysec_importer_v2/PYSEC-2020-1
    - pysec_importer_v2/PYSEC-2020-10
    - pysec_importer_v2/PYSEC-2020-11
    - pysec_importer_v2/PYSEC-2020-12
    - pysec_importer_v2/PYSEC-2020-13
    - pysec_importer_v2/PYSEC-2020-160
    - pysec_importer_v2/PYSEC-2020-161
    - pysec_importer_v2/PYSEC-2020-179
    - pysec_importer_v2/PYSEC-2020-180
    - pysec_importer_v2/PYSEC-2020-206
    - pysec_importer_v2/PYSEC-2020-207
    - pysec_importer_v2/PYSEC-2020-208
    - pysec_importer_v2/PYSEC-2020-210
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2020-5
    - pysec_importer_v2/PYSEC-2020-6
    - pysec_importer_v2/PYSEC-2020-7
    - pysec_importer_v2/PYSEC-2020-8
    - pysec_importer_v2/PYSEC-2020-9
    - pysec_importer_v2/PYSEC-2021-1
    - pysec_importer_v2/PYSEC-2021-105
    - pysec_importer_v2/PYSEC-2021-106
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2021-358
    - pysec_importer_v2/PYSEC-2022-164
  fixing_advisories: []
