- purl: pkg:pypi/esphome@2023.12.9
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-5925-88xh-6h99
    - github_osv_importer_v2/GHSA-8p25-3q46-8q2p
    - github_osv_importer_v2/GHSA-9p43-hj5j-96h5
    - github_osv_importer_v2/GHSA-mxh2-ccgj-8635
    - gitlab_importer_v2/pypi/esphome/CVE-2024-27081
    - gitlab_importer_v2/pypi/esphome/CVE-2024-27287
    - gitlab_importer_v2/pypi/esphome/CVE-2024-29019
  fixing_advisories: []
