- purl: pkg:rpm/redhat/ansible@2.2.1.0-1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0195
    - redhat_importer_v2/RHSA-2017:0515
- purl: pkg:rpm/redhat/ansible@2.2.1.0-1.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0195
    - redhat_importer_v2/RHSA-2017:0515
