- purl: pkg:deb/ubuntu/prometheus-blackbox-exporter@0.13.0%2Bds-2
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-16248
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-26735
  fixing_advisories: []
