- purl: pkg:deb/debian/kubernetes@1.7.16%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2017-1002101
    - debian_importer_v2/kubernetes/CVE-2017-1002102
