- purl: pkg:pypi/ansible@11.6.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2021-125
  fixing_advisories: []
