- purl: pkg:rpm/redhat/ansible@2.6.14-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0433
- purl: pkg:rpm/redhat/ansible@2.6.14-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0433
