- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.98-1.git.92.7ebe477.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:0636
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.98-1.git.92.7ebe477.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:0636
