- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=riscv64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=loongarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=loongarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=riscv64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/edge/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.23/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=loongarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.19/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=riscv64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.21/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=riscv64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.20/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.17/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.16/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86_64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=x86&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=s390x&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armv7&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=armhf&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=aarch64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.18/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=loongarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=ppc64le&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
- purl: pkg:apk/alpine/docker@20.10.20-r0?arch=riscv64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.22/20.10.20-r0/CVE-2022-39253
