- purl: pkg:maven/ansible/ansible@2.8.10
  affected_by_advisories:
    - project-kb-statements_v2/CVE-2020-1734
  fixing_advisories:
    - project-kb-statements_v2/CVE-2018-16859
    - project-kb-statements_v2/CVE-2019-10156
    - project-kb-statements_v2/CVE-2019-14864
