- purl: pkg:deb/ubuntu/cloud-init@22.2-0ubuntu1~20.04.3?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
