- purl: pkg:rpm/redhat/prometheus-promu@0-5.git85ceabc.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2769
    - redhat_importer_v2/RHSA-2019:3265
