- purl: pkg:deb/ubuntu/ansible@1.9.4-1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-3096
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-8628
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-9587
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2017-7466
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2017-7481
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10875
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16837
  fixing_advisories: []
- purl: pkg:deb/ubuntu/ansible@1.9.4-1?arch=source&distro=esm-apps/xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-8614
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2017-7473
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-10206
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14846
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14904
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10684
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10729
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10744
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14330
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14332
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14365
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1733
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1734
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1736
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1737
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1738
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1739
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1740
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1746
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1753
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25635
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25636
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25646
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20178
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20180
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20191
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20228
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3447
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3583
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4237
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4380
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4567
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5115
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5189
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5764
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-0690
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11079
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-8775
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9902
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-14010
  fixing_advisories: []
