- purl: pkg:deb/debian/ansible@2.6.1%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2018-10874
    - debian_importer_v2/ansible/CVE-2018-10875
