- purl: pkg:rpm/redhat/ansible@2.6.19-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2545
    - redhat_importer_v2/RHSA-2019:3744
    - redhat_importer_v2/RHSA-2019:3789
- purl: pkg:rpm/redhat/ansible@2.6.19-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2545
    - redhat_importer_v2/RHSA-2019:3744
    - redhat_importer_v2/RHSA-2019:3789
