- purl: pkg:rpm/redhat/cloud-init@20.3-10.el8_4.5?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3081
- purl: pkg:rpm/redhat/cloud-init@20.3-10.el8_4.5?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3081
