- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=x86_64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=armhf&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=armv7&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=ppc64le&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=s390x&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=aarch64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.5-r0?arch=x86&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.17/2.40.5-r0/CVE-2022-46146
