- purl: pkg:rpm/redhat/prometheus-node-exporter@3.10.66-1.git.1060.f6046fd.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2709
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.10.66-1.git.1060.f6046fd.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:2709
