- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=riscv64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.19/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=loongarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=loongarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=riscv64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.21/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.20/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armv7&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=armhf&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=loongarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=riscv64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/edge/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86_64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=riscv64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=aarch64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.18/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=s390x&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=riscv64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=x86&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.22/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=ppc64le&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
- purl: pkg:apk/alpine/prometheus@2.40.4-r1?arch=loongarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/prometheus/v3.23/2.40.4-r1/CVE-2022-46146
