- purl: pkg:rpm/redhat/cloud-init@19.4-1.el8.7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3050
- purl: pkg:rpm/redhat/cloud-init@19.4-1.el8.7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3050
