- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-6.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:4807
- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-6.el8?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:4807
