- purl: pkg:rpm/redhat/grafana@9.2.10-8.el9_3?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1501
- purl: pkg:rpm/redhat/grafana@9.2.10-8.el9_3?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1501
- purl: pkg:rpm/redhat/grafana@9.2.10-8.el9_3?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1501
- purl: pkg:rpm/redhat/grafana@9.2.10-8.el9_3?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1501
- purl: pkg:rpm/redhat/grafana@9.2.10-8.el9_3?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:1501
