- purl: pkg:deb/ubuntu/cloud-init@22.2-0ubuntu1~18.04.2?arch=source&distro=bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
