- purl: pkg:rpm/redhat/rubygem-prometheus-client@0.8.0-1.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:1816
    - redhat_importer_v2/RHBA-2018:2652
- purl: pkg:rpm/redhat/rubygem-prometheus-client@0.8.0-1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:1816
    - redhat_importer_v2/RHBA-2018:2652
