- purl: pkg:deb/debian/kubernetes@1.31.4%2Bds-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2020-8554
    - debian_importer_v2/kubernetes/CVE-2021-25743
