- purl: pkg:rpm/redhat/ansible@2.4.4.0-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:1328
    - redhat_importer_v2/RHSA-2018:1972
- purl: pkg:rpm/redhat/ansible@2.4.4.0-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:1328
    - redhat_importer_v2/RHSA-2018:1972
