- purl: pkg:rpm/redhat/cloud-init@23.4-7.el9_4.13?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10876
- purl: pkg:rpm/redhat/cloud-init@23.4-7.el9_4.13?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:10876
