- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-1.gitceca8c1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:3188
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-1.gitceca8c1.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:3188
