- purl: pkg:rpm/redhat/docker@1.13.1-94.gitb2f74b2.el7?arch=src&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0487
- purl: pkg:rpm/redhat/docker@1.13.1-94.gitb2f74b2.el7?arch=aarch64&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0487
- purl: pkg:rpm/redhat/docker@1.13.1-94.gitb2f74b2.el7?arch=s390x&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0487
- purl: pkg:rpm/redhat/docker@1.13.1-94.gitb2f74b2.el7?arch=ppc64le&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0487
- purl: pkg:rpm/redhat/docker@1.13.1-94.gitb2f74b2.el7?arch=x86_64&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0487
