- purl: pkg:rpm/redhat/grafana@7.3.6-9.el8_4?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:8683
- purl: pkg:rpm/redhat/grafana@7.3.6-9.el8_4?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:8683
