- purl: pkg:rpm/redhat/grafana@5.2.4-6.el7rhgs?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:1486
- purl: pkg:rpm/redhat/grafana@5.2.4-6.el7rhgs?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:1486
