- purl: pkg:rpm/redhat/ansible@2.3.0.0-4.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:1685
- purl: pkg:rpm/redhat/ansible@2.3.0.0-4.el7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:1685
