- purl: pkg:pypi/ansible@2.10.6
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
  fixing_advisories: []
