- purl: pkg:deb/debian/kubernetes@1.5.5%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2016-7075
    - debian_importer_v2/kubernetes/CVE-2017-1000056
