- purl: pkg:rpm/redhat/grafana@4.6.4-1.el7rhgs?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3829
- purl: pkg:rpm/redhat/grafana@4.6.4-1.el7rhgs?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3829
