- purl: pkg:rpm/redhat/cloud-init@23.1.1-10.el8?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6943
- purl: pkg:rpm/redhat/cloud-init@23.1.1-10.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6943
