- purl: pkg:rpm/redhat/ansible@2.9.7-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:1541
    - redhat_importer_v2/RHSA-2020:1542
- purl: pkg:rpm/redhat/ansible@2.9.7-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:1541
    - redhat_importer_v2/RHSA-2020:1542
