- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=x86&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=x86_64&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=aarch64&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=aarch64&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=armhf&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=mips64&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=s390x&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=armv7&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=x86&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=ppc64le&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=armhf&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=armv7&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=x86_64&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=ppc64le&distroversion=v3.11&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.11/2.9.3-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.9.3-r0?arch=s390x&distroversion=v3.12&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.12/2.9.3-r0/CVE-2019-14905
