- purl: pkg:rpm/redhat/cloud-init@21.1-19.el9_0.7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11295
- purl: pkg:rpm/redhat/cloud-init@21.1-19.el9_0.7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11295
