- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.15/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=mips64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.19/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=loongarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=riscv64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.20/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=riscv64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.17/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=riscv64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=loongarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.14/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=riscv64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.22/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=loongarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/edge/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.13&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.13/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=riscv64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=loongarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.23/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.21/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=aarch64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armhf&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=armv7&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=ppc64le&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=s390x&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
- purl: pkg:apk/alpine/grafana@6.3.4-r0?arch=x86_64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.18/6.3.4-r0/CVE-2019-15043
