- purl: pkg:rpm/redhat/prometheus-node-exporter@3.10.72-1.git.1060.64daa26.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3549
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.10.72-1.git.1060.64daa26.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3549
