- purl: pkg:deb/ubuntu/ansible@7.7.0%2Bdfsg-1?arch=source&distro=noble
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14332
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14365
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1734
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1736
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1738
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1753
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25635
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25636
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25646
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20178
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20180
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20191
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20228
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3447
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3583
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4237
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4380
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5115
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5189
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-0690
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11079
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-8775
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9902
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-14010
  fixing_advisories: []
