- purl: pkg:pypi/esphome@2024.3.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-mxh2-ccgj-8635
  fixing_advisories:
    - github_osv_importer_v2/GHSA-5925-88xh-6h99
    - gitlab_importer_v2/pypi/esphome/CVE-2024-29019
