- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.420-1.git.0.9300c91.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.420-1.git.0.9300c91.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
