- purl: pkg:apk/alpine/docker@18.09.8?arch=ppc64le&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=armv7&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=armhf&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=x86&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=armhf&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=aarch64&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=s390x&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=x86&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=x86_64&distroversion=v3.11&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.11/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=aarch64&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=x86_64&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=armv7&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=ppc64le&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
- purl: pkg:apk/alpine/docker@18.09.8?arch=s390x&distroversion=v3.9&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/docker/v3.9/18.09.8/CVE-2019-13509
