- purl: pkg:rpm/redhat/ansible@2.9.1-1.el8?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3927
    - redhat_importer_v2/RHSA-2019:3928
- purl: pkg:rpm/redhat/ansible@2.9.1-1.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3927
    - redhat_importer_v2/RHSA-2019:3928
