- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.7.0
  affected_by_advisories:
    - gitlab_importer_v2/maven/org.csanchez.jenkins.plugins/kubernetes/CVE-2018-1000187
  fixing_advisories: []
