- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-18.el8.1?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6272
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-18.el8.1?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6272
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-18.el8.1?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6272
- purl: pkg:rpm/redhat/servicemesh-prometheus@2.14.0-18.el8.1?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:6272
