- purl: pkg:deb/ubuntu/golang-github-prometheus-client-golang@1.21.1-1?arch=source&distro=questing
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21698
  fixing_advisories: []
