- purl: pkg:rpm/redhat/rubygem-prometheus-client@4.1.0-1.el8sat?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6818
- purl: pkg:rpm/redhat/rubygem-prometheus-client@4.1.0-1.el8sat?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2023:6818
