- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=s390x&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=aarch64&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=armhf&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=armv7&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=ppc64le&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=x86&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
- purl: pkg:apk/alpine/ansible@2.7.16-r0?arch=x86_64&distroversion=v3.9&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14864
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14904
    - alpine_linux_importer_v2/ansible/v3.9/2.7.16-r0/CVE-2019-14905
