- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=noble
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-7075
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-7010
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8552
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8554
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8555
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8557
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8558
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8559
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8561
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8562
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8563
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8564
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8565
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8566
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25741
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2431
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2727
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2728
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3676
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3893
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-10220
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-3177
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-5321
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-7598
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9486
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9594
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-0426
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-4563
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=jammy
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-7075
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-7010
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8552
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8554
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8555
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8557
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8558
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8559
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8561
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8562
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8563
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8564
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8565
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8566
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25741
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2431
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2727
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2728
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3676
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3893
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-10220
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-3177
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-5321
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-7598
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9486
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9594
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-0426
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-4563
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=esm-apps/focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-7075
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-7010
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8552
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8554
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8555
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8557
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8558
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8559
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8561
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8562
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8563
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8564
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8565
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-8566
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-25741
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2431
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2727
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-2728
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3676
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-3893
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-10220
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-3177
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-5321
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-7598
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9594
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-0426
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-4563
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9486
  fixing_advisories: []
- purl: pkg:deb/ubuntu/kubernetes@1.0?arch=source&distro=oracular
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9486
  fixing_advisories: []
