- purl: pkg:pypi/ansible@2.7.18
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-4r65-35qq-ch8j
    - github_osv_importer_v2/GHSA-5rrg-rr89-x9mv
    - github_osv_importer_v2/GHSA-785x-qw4v-6872
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-cpx3-93w7-457x
    - github_osv_importer_v2/GHSA-f556-49jc-4rvc
    - github_osv_importer_v2/GHSA-h39q-95q5-9jfp
    - github_osv_importer_v2/GHSA-j667-c2hm-f2wp
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - github_osv_importer_v2/GHSA-r6h7-5pq2-j77h
    - github_osv_importer_v2/GHSA-vp9j-rghq-8jhh
    - github_osv_importer_v2/GHSA-wv5p-gmmv-wh9v
    - github_osv_importer_v2/GHSA-x7jh-595q-wq82
    - pypa_importer_v2/PYSEC-2018-60
    - pypa_importer_v2/PYSEC-2019-171
    - pypa_importer_v2/PYSEC-2020-208
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2020-3
    - pypa_importer_v2/PYSEC-2021-1
    - pypa_importer_v2/PYSEC-2021-105
    - pypa_importer_v2/PYSEC-2021-106
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pypa_importer_v2/PYSEC-2021-358
    - pypa_importer_v2/PYSEC-2022-164
    - pysec_importer_v2/PYSEC-2018-60
    - pysec_importer_v2/PYSEC-2019-171
    - pysec_importer_v2/PYSEC-2020-208
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2021-1
    - pysec_importer_v2/PYSEC-2021-105
    - pysec_importer_v2/PYSEC-2021-106
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2021-358
    - pysec_importer_v2/PYSEC-2022-164
  fixing_advisories:
    - github_osv_importer_v2/GHSA-86hp-cj9j-33vv
    - github_osv_importer_v2/GHSA-gfr2-qpxh-qj9m
    - pypa_importer_v2/PYSEC-2020-210
    - pysec_importer_v2/PYSEC-2020-210
