- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.4.0-1.gitafc7dfe.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:2921
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.4.0-1.gitafc7dfe.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:2921
