- purl: pkg:rpm/redhat/cloud-init@18.5-12.el8_2.3?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3644
- purl: pkg:rpm/redhat/cloud-init@18.5-12.el8_2.3?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:3644
