- purl: pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1ubuntu0.1?arch=source&distro=bionic
  affected_by_advisories: []
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-2686
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10855
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10874
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-10875
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16837
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2018-16876
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-10156
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-3828
- purl: pkg:deb/ubuntu/ansible@2.5.1%2Bdfsg-1ubuntu0.1?arch=source&distro=esm-apps/bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2017-7473
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-10206
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14846
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14858
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14904
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-14905
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10684
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10685
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10729
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10744
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14330
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14332
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14365
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1733
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1734
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1736
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1737
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1738
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1739
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1740
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1746
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1753
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25635
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25636
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25646
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20178
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20180
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20191
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-20228
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3447
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3532
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3533
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3583
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2568
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-3697
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4237
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4380
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4567
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5115
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5189
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5764
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-0690
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11079
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-8775
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9902
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-14010
  fixing_advisories: []
