- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-17.gitd5383c5.el8?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:5436
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-17.gitd5383c5.el8?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:5436
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-17.gitd5383c5.el8?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:5436
- purl: pkg:rpm/redhat/openshift-prometheus-promu@0.15.0-17.gitd5383c5.el8?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:5436
