- purl: pkg:deb/ubuntu/helm@2.8.8-1?arch=source&distro=bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-1010275
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-11013
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-21303
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
  fixing_advisories: []
