- purl: pkg:rpm/redhat/rubygem-prometheus-client@4.2.5-1.el9sat?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:19721
- purl: pkg:rpm/redhat/rubygem-prometheus-client@4.2.5-1.el9sat?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:19721
