- purl: pkg:deb/debian/ansible@1.3.4%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2013-2233
    - debian_importer_v2/ansible/CVE-2013-4259
