- purl: pkg:rpm/redhat/prometheus@3.11.346-1.git.5026.2eafa83.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:5363
- purl: pkg:rpm/redhat/prometheus@3.11.346-1.git.5026.2eafa83.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2020:5363
