- purl: pkg:deb/ubuntu/cloud-init@23.1.2-0ubuntu0~18.04.1%2Besm1?arch=source&distro=esm-infra/bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5536
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11584
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
