- purl: pkg:deb/debian/ansible@1.9.2%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2015-3908
    - debian_importer_v2/ansible/CVE-2015-6240
