- purl: pkg:deb/ubuntu/cloud-init@22.1-14-g2e17a0d6-0ubuntu1~20.04.2?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
