- purl: pkg:deb/debian/ansible@1.5.5%2Bdfsg-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2014-4657
    - debian_importer_v2/ansible/CVE-2014-4658
    - debian_importer_v2/ansible/CVE-2014-4659
    - debian_importer_v2/ansible/CVE-2014-4660
