- purl: pkg:rpm/redhat/ansible@2.6.11-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3836
    - redhat_importer_v2/RHSA-2019:0564
    - redhat_importer_v2/RHSA-2019:0590
- purl: pkg:rpm/redhat/ansible@2.6.11-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3836
    - redhat_importer_v2/RHSA-2019:0564
    - redhat_importer_v2/RHSA-2019:0590
