- purl: pkg:rpm/redhat/docker@0.11.1-22.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2014:0820
- purl: pkg:rpm/redhat/docker@0.11.1-22.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2014:0820
