- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=loongarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=loongarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=riscv64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.15&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.15/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.20&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.20/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=loongarch64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=riscv64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=edge&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/edge/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=riscv64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=riscv64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.23&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.23/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.18&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.18/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.16/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.17&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.17/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=loongarch64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=riscv64&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.21&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.21/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.22&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.22/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.19&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.19/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=x86_64&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=ppc64le&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=s390x&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=aarch64&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armv7&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
- purl: pkg:apk/alpine/cloud-init@21.1-r1?arch=armhf&distroversion=v3.14&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/cloud-init/v3.14/21.1-r1/CVE-2021-3429
