- purl: pkg:rpm/redhat/cloud-init@23.4-7.el8_10.10?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11324
- purl: pkg:rpm/redhat/cloud-init@23.4-7.el8_10.10?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11324
