- purl: pkg:deb/ubuntu/cloud-init@24.4.1-0ubuntu0~20.04.3%2Besm1?arch=source&distro=esm-infra/focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5536
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11584
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-6174
