- purl: pkg:rpm/redhat/docker@1.12.6-79.git5680db5.el7?arch=x86_64&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0408
- purl: pkg:rpm/redhat/docker@1.12.6-79.git5680db5.el7?arch=src&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:0408
