- purl: pkg:deb/ubuntu/cloud-init@21.3-1-g6803368d-0ubuntu1~18.04.3?arch=source&distro=bionic
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-2084
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-1786
  fixing_advisories: []
