- purl: pkg:deb/debian/ansible@2.10.7-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2021-20178
    - debian_importer_v2/ansible/CVE-2021-20180
    - debian_importer_v2/ansible/CVE-2021-20191
