- purl: pkg:maven/org.jenkins-ci.plugins/ansible@205.v4cb
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-38hw-368m-7jmg
    - github_osv_importer_v2/GHSA-97wp-63wq-hfwh
    - gitlab_importer_v2/maven/org.jenkins-ci.plugins/ansible/CVE-2023-32983
