- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.161-1.git.1.823bae5.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:0017
- purl: pkg:rpm/redhat/prometheus-alertmanager@3.11.161-1.git.1.823bae5.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:0017
