- purl: pkg:pypi/esphome@2024.2.0
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-5925-88xh-6h99
    - github_osv_importer_v2/GHSA-9p43-hj5j-96h5
    - github_osv_importer_v2/GHSA-mxh2-ccgj-8635
  fixing_advisories: []
