- purl: pkg:maven/org.csanchez.jenkins.plugins/kubernetes@1.26.5
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-fh5w-p2j4-4p8x
    - github_osv_importer_v2/GHSA-g2r3-4g8q-h5rj
    - github_osv_importer_v2/GHSA-rr6j-37cv-c7x7
