- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=x86_64&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=aarch64&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=armhf&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=ppc64le&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=s390x&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
- purl: pkg:apk/alpine/ansible@2.5.15-r0?arch=x86&distroversion=v3.8&reponame=main
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/ansible/v3.8/2.5.15-r0/CVE-2019-3828
