- purl: pkg:rpm/redhat/ansible@2.4.6.0-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3788
    - redhat_importer_v2/RHSA-2018:2152
    - redhat_importer_v2/RHSA-2018:2585
    - redhat_importer_v2/RHSA-2019:0054
- purl: pkg:rpm/redhat/ansible@2.4.6.0-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3788
    - redhat_importer_v2/RHSA-2018:2152
    - redhat_importer_v2/RHSA-2018:2585
    - redhat_importer_v2/RHSA-2019:0054
