- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.59-1.git.1063.dce4999.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:0024
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.59-1.git.1063.dce4999.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2019:0024
