- purl: pkg:npm/%40ag-grid-enterprise/charts@32.0.1
  affected_by_advisories: []
  fixing_advisories:
    - github_osv_importer_v2/GHSA-328p-362g-r48j
    - gitlab_importer_v2/npm/@ag-grid-enterprise/charts/CVE-2024-39001
