- purl: pkg:rpm/redhat/prometheus-promu@0-2.git85ceabc.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:0489
    - redhat_importer_v2/RHBA-2018:1816
