- purl: pkg:pypi/ansible@1.2.2
  affected_by_advisories:
    - github_osv_importer_v2/GHSA-2pfh-q76x-gwvm
    - github_osv_importer_v2/GHSA-3m8p-xpm6-8ww3
    - github_osv_importer_v2/GHSA-3xvg-x47j-x75w
    - github_osv_importer_v2/GHSA-49m5-2838-q2rv
    - github_osv_importer_v2/GHSA-4cvm-5776-jx9f
    - github_osv_importer_v2/GHSA-4r65-35qq-ch8j
    - github_osv_importer_v2/GHSA-5g4v-2pc6-4hh4
    - github_osv_importer_v2/GHSA-5rrg-rr89-x9mv
    - github_osv_importer_v2/GHSA-5xm4-jmpw-p6j3
    - github_osv_importer_v2/GHSA-64cw-m57j-65xj
    - github_osv_importer_v2/GHSA-6667-f46p-pg88
    - github_osv_importer_v2/GHSA-66c7-5pwv-mm3j
    - github_osv_importer_v2/GHSA-74vq-h4q8-x6jv
    - github_osv_importer_v2/GHSA-785x-qw4v-6872
    - github_osv_importer_v2/GHSA-893h-35v4-mxqx
    - github_osv_importer_v2/GHSA-8f4m-hccc-8qph
    - github_osv_importer_v2/GHSA-8ggh-xwr9-3373
    - github_osv_importer_v2/GHSA-923p-fr2c-g5m2
    - github_osv_importer_v2/GHSA-cmwx-9m2h-x7v4
    - github_osv_importer_v2/GHSA-f556-49jc-4rvc
    - github_osv_importer_v2/GHSA-f85h-23mf-2fwh
    - github_osv_importer_v2/GHSA-fc4h-467w-46rh
    - github_osv_importer_v2/GHSA-fj24-ghp9-39v3
    - github_osv_importer_v2/GHSA-g4mq-6fp5-qwcf
    - github_osv_importer_v2/GHSA-grgm-pph5-j5h7
    - github_osv_importer_v2/GHSA-gwr8-5j83-483c
    - github_osv_importer_v2/GHSA-h39q-95q5-9jfp
    - github_osv_importer_v2/GHSA-hwrm-63v2-42g4
    - github_osv_importer_v2/GHSA-j569-fghw-f9rx
    - github_osv_importer_v2/GHSA-j667-c2hm-f2wp
    - github_osv_importer_v2/GHSA-jg4f-jqm5-4mgq
    - github_osv_importer_v2/GHSA-jpvw-p8pr-9g2x
    - github_osv_importer_v2/GHSA-m956-frf4-m2wr
    - github_osv_importer_v2/GHSA-pcqv-c46v-2p4v
    - github_osv_importer_v2/GHSA-pm48-cvv2-29q5
    - github_osv_importer_v2/GHSA-qg47-5px9-32g7
    - github_osv_importer_v2/GHSA-r6h7-5pq2-j77h
    - github_osv_importer_v2/GHSA-rh6x-qvg7-rrmj
    - github_osv_importer_v2/GHSA-rh6x-qvg7-rrmj
    - github_osv_importer_v2/GHSA-v735-2pp6-h86r
    - github_osv_importer_v2/GHSA-vcg8-98q8-g7mj
    - github_osv_importer_v2/GHSA-vp9j-rghq-8jhh
    - github_osv_importer_v2/GHSA-w578-j992-554x
    - github_osv_importer_v2/GHSA-w64c-pxjj-h866
    - github_osv_importer_v2/GHSA-wqq5-c89p-3wc3
    - github_osv_importer_v2/GHSA-wv5p-gmmv-wh9v
    - github_osv_importer_v2/GHSA-wwwh-47wp-m522
    - github_osv_importer_v2/GHSA-x4cm-m36h-c6qj
    - gitlab_importer_v2/pypi/ansible/CVE-2013-4259
    - gitlab_importer_v2/pypi/ansible/CVE-2013-4260
    - gitlab_importer_v2/pypi/ansible/CVE-2014-2686
    - gitlab_importer_v2/pypi/ansible/CVE-2014-3498
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4657
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4658
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4659
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4660
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4678
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4966
    - gitlab_importer_v2/pypi/ansible/CVE-2014-4967
    - gitlab_importer_v2/pypi/ansible/CVE-2015-3908
    - gitlab_importer_v2/pypi/ansible/CVE-2015-6240
    - gitlab_importer_v2/pypi/ansible/CVE-2016-3096
    - gitlab_importer_v2/pypi/ansible/CVE-2016-8614
    - gitlab_importer_v2/pypi/ansible/CVE-2016-8628
    - gitlab_importer_v2/pypi/ansible/CVE-2016-8647
    - gitlab_importer_v2/pypi/ansible/CVE-2016-9587
    - gitlab_importer_v2/pypi/ansible/CVE-2017-7466
    - gitlab_importer_v2/pypi/ansible/CVE-2017-7481
    - gitlab_importer_v2/pypi/ansible/CVE-2018-16859
    - gitlab_importer_v2/pypi/ansible/CVE-2018-16876
    - gitlab_importer_v2/pypi/ansible/CVE-2019-10156
    - gitlab_importer_v2/pypi/ansible/CVE-2019-14904
    - gitlab_importer_v2/pypi/ansible/CVE-2019-3828
    - gitlab_importer_v2/pypi/ansible/CVE-2020-10729
    - gitlab_importer_v2/pypi/ansible/CVE-2020-10744
    - gitlab_importer_v2/pypi/ansible/CVE-2020-14330
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1733
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1734
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1735
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1737
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1738
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1739
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1740
    - gitlab_importer_v2/pypi/ansible/CVE-2020-1753
    - gitlab_importer_v2/pypi/ansible/CVE-2020-20178
    - gitlab_importer_v2/pypi/ansible/CVE-2020-25635
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20178
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20180
    - gitlab_importer_v2/pypi/ansible/CVE-2021-20191
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3583
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3620
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5115
    - gitlab_importer_v2/pypi/ansible/CVE-2023-5764
    - gitlab_importer_v2/pypi/ansible/CVE-2025-14010
    - pypa_importer_v2/PYSEC-2013-1
    - pypa_importer_v2/PYSEC-2013-2
    - pypa_importer_v2/PYSEC-2015-1
    - pypa_importer_v2/PYSEC-2016-1
    - pypa_importer_v2/PYSEC-2017-2
    - pypa_importer_v2/PYSEC-2017-3
    - pypa_importer_v2/PYSEC-2018-37
    - pypa_importer_v2/PYSEC-2018-38
    - pypa_importer_v2/PYSEC-2018-39
    - pypa_importer_v2/PYSEC-2018-40
    - pypa_importer_v2/PYSEC-2018-41
    - pypa_importer_v2/PYSEC-2018-44
    - pypa_importer_v2/PYSEC-2018-58
    - pypa_importer_v2/PYSEC-2018-60
    - pypa_importer_v2/PYSEC-2018-81
    - pypa_importer_v2/PYSEC-2019-2
    - pypa_importer_v2/PYSEC-2019-4
    - pypa_importer_v2/PYSEC-2020-10
    - pypa_importer_v2/PYSEC-2020-11
    - pypa_importer_v2/PYSEC-2020-12
    - pypa_importer_v2/PYSEC-2020-161
    - pypa_importer_v2/PYSEC-2020-198
    - pypa_importer_v2/PYSEC-2020-199
    - pypa_importer_v2/PYSEC-2020-200
    - pypa_importer_v2/PYSEC-2020-201
    - pypa_importer_v2/PYSEC-2020-202
    - pypa_importer_v2/PYSEC-2020-203
    - pypa_importer_v2/PYSEC-2020-204
    - pypa_importer_v2/PYSEC-2020-205
    - pypa_importer_v2/PYSEC-2020-210
    - pypa_importer_v2/PYSEC-2020-220
    - pypa_importer_v2/PYSEC-2020-221
    - pypa_importer_v2/PYSEC-2020-3
    - pypa_importer_v2/PYSEC-2020-5
    - pypa_importer_v2/PYSEC-2020-6
    - pypa_importer_v2/PYSEC-2020-7
    - pypa_importer_v2/PYSEC-2020-8
    - pypa_importer_v2/PYSEC-2020-9
    - pypa_importer_v2/PYSEC-2021-1
    - pypa_importer_v2/PYSEC-2021-105
    - pypa_importer_v2/PYSEC-2021-106
    - pypa_importer_v2/PYSEC-2021-124
    - pypa_importer_v2/PYSEC-2021-125
    - pypa_importer_v2/PYSEC-2021-126
    - pypa_importer_v2/PYSEC-2021-358
    - pypa_importer_v2/PYSEC-2022-164
    - pysec_importer_v2/PYSEC-2013-1
    - pysec_importer_v2/PYSEC-2013-2
    - pysec_importer_v2/PYSEC-2015-1
    - pysec_importer_v2/PYSEC-2016-1
    - pysec_importer_v2/PYSEC-2017-2
    - pysec_importer_v2/PYSEC-2017-3
    - pysec_importer_v2/PYSEC-2018-37
    - pysec_importer_v2/PYSEC-2018-38
    - pysec_importer_v2/PYSEC-2018-39
    - pysec_importer_v2/PYSEC-2018-40
    - pysec_importer_v2/PYSEC-2018-41
    - pysec_importer_v2/PYSEC-2018-44
    - pysec_importer_v2/PYSEC-2018-58
    - pysec_importer_v2/PYSEC-2018-60
    - pysec_importer_v2/PYSEC-2018-81
    - pysec_importer_v2/PYSEC-2019-2
    - pysec_importer_v2/PYSEC-2019-4
    - pysec_importer_v2/PYSEC-2019-72
    - pysec_importer_v2/PYSEC-2019-74
    - pysec_importer_v2/PYSEC-2020-10
    - pysec_importer_v2/PYSEC-2020-11
    - pysec_importer_v2/PYSEC-2020-12
    - pysec_importer_v2/PYSEC-2020-161
    - pysec_importer_v2/PYSEC-2020-180
    - pysec_importer_v2/PYSEC-2020-198
    - pysec_importer_v2/PYSEC-2020-199
    - pysec_importer_v2/PYSEC-2020-200
    - pysec_importer_v2/PYSEC-2020-201
    - pysec_importer_v2/PYSEC-2020-202
    - pysec_importer_v2/PYSEC-2020-203
    - pysec_importer_v2/PYSEC-2020-204
    - pysec_importer_v2/PYSEC-2020-205
    - pysec_importer_v2/PYSEC-2020-210
    - pysec_importer_v2/PYSEC-2020-220
    - pysec_importer_v2/PYSEC-2020-221
    - pysec_importer_v2/PYSEC-2020-3
    - pysec_importer_v2/PYSEC-2020-5
    - pysec_importer_v2/PYSEC-2020-6
    - pysec_importer_v2/PYSEC-2020-7
    - pysec_importer_v2/PYSEC-2020-8
    - pysec_importer_v2/PYSEC-2020-9
    - pysec_importer_v2/PYSEC-2021-1
    - pysec_importer_v2/PYSEC-2021-105
    - pysec_importer_v2/PYSEC-2021-106
    - pysec_importer_v2/PYSEC-2021-124
    - pysec_importer_v2/PYSEC-2021-125
    - pysec_importer_v2/PYSEC-2021-126
    - pysec_importer_v2/PYSEC-2021-358
    - pysec_importer_v2/PYSEC-2022-164
  fixing_advisories:
    - gitlab_importer_v2/pypi/ansible/CVE-2021-3447
    - pypa_importer_v2/PYSEC-2021-107
    - pysec_importer_v2/PYSEC-2021-107
