- purl: pkg:rpm/redhat/ansible@2.6.20-1.el7ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3201
    - redhat_importer_v2/RHSA-2020:0756
- purl: pkg:rpm/redhat/ansible@2.6.20-1.el7ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3201
    - redhat_importer_v2/RHSA-2020:0756
