- purl: pkg:rpm/redhat/helm@3.15.4-60.el9?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2025:0507
- purl: pkg:rpm/redhat/helm@3.15.4-60.el9?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2025:0507
- purl: pkg:rpm/redhat/helm@3.15.4-60.el9?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2025:0507
- purl: pkg:rpm/redhat/helm@3.15.4-60.el9?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2025:0507
- purl: pkg:rpm/redhat/helm@3.15.4-60.el9?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHEA-2025:0507
