- purl: pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1?arch=source&distro=trusty/esm
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-3498
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-4658
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-4660
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-4678
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-4966
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2014-4967
  fixing_advisories: []
- purl: pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1?arch=source&distro=trusty
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2013-2233
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2013-4259
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2013-4260
  fixing_advisories: []
- purl: pkg:deb/ubuntu/ansible@1.4.3%2Bdfsg-1?arch=source&distro=esm-infra-legacy/trusty
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2016-8614
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2017-7473
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-10684
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14330
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14332
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-14365
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1734
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1735
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1736
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1737
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1738
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1739
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1746
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-1753
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25635
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25636
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-25646
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3447
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4237
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4380
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-4567
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5115
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-5189
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-0690
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-11079
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-8775
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-9902
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-14010
  fixing_advisories: []
