- purl: pkg:rpm/redhat/grafana-prometheus@6.2.2-7.el8_1?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3769
- purl: pkg:rpm/redhat/grafana-prometheus@6.2.2-7.el8_1?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3769
- purl: pkg:rpm/redhat/grafana-prometheus@6.2.2-7.el8_1?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3769
- purl: pkg:rpm/redhat/grafana-prometheus@6.2.2-7.el8_1?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3769
