- purl: pkg:deb/ubuntu/golang-github-prometheus-client-golang@0.9.2-0ubuntu3?arch=source&distro=focal
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2022-21698
  fixing_advisories: []
