- purl: pkg:rpm/redhat/grafana@5.2.4-3.el7cp?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:1518
- purl: pkg:rpm/redhat/grafana@5.2.4-3.el7cp?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:1518
