- purl: pkg:deb/debian/kubernetes@1.19.3-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/kubernetes/CVE-2020-8564
    - debian_importer_v2/kubernetes/CVE-2020-8566
