- purl: pkg:rpm/redhat/docker@1.12.5-14.el7?arch=src&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0116
- purl: pkg:rpm/redhat/docker@1.12.5-14.el7?arch=x86_64&epoch=2
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2017:0116
