- purl: pkg:deb/ubuntu/helm@3.8.4-1?arch=source&distro=noble
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2020-11013
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-25620
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2024-26147
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32386
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2025-32387
  fixing_advisories: []
