- purl: pkg:deb/ubuntu/cloud-init@18.5-45-g3554ffe8-0ubuntu1~16.04.1?arch=source&distro=xenial
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2021-3429
  fixing_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2019-0816
