- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960.el8?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3248
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960.el8?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3248
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960.el8?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3248
- purl: pkg:rpm/redhat/golang-github-prometheus-promu@0.5.0-4.git642a960.el8?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:3248
