- purl: pkg:maven/ansible/ansible@2.8.2
  affected_by_advisories:
    - project-kb-statements_v2/CVE-2019-14864
  fixing_advisories:
    - project-kb-statements_v2/CVE-2017-7481
    - project-kb-statements_v2/CVE-2018-16859
    - project-kb-statements_v2/CVE-2019-10156
- purl: pkg:maven/ansible/ansible@2.8.2
  affected_by_advisories:
    - project-kb-statements_v2/CVE-2019-14864
  fixing_advisories:
    - project-kb-statements_v2/CVE-2017-7481
    - project-kb-statements_v2/CVE-2018-16859
    - project-kb-statements_v2/CVE-2019-10156
