- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.2.el7cf?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3816
- purl: pkg:rpm/redhat/httpd-configmap-generator@0.2.2-1.2.el7cf?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2018:3816
