- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.420-1.git.1062.26157c1.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.420-1.git.1062.26157c1.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:1147
