- purl: pkg:rpm/redhat/ansible@2.8.16-1.el8ae?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:4195
- purl: pkg:rpm/redhat/ansible@2.8.16-1.el8ae?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:4195
