- purl: pkg:rpm/redhat/cloud-init@21.1-15.el8_6.4?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11337
- purl: pkg:rpm/redhat/cloud-init@21.1-15.el8_6.4?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11337
