- purl: pkg:deb/debian/golang-github-prometheus-client-golang@1.9.0-2?distro=trixie
  affected_by_advisories:
    - debian_importer_v2/golang-github-prometheus-client-golang/CVE-2022-21698
    - debian_importer_v2/golang-github-prometheus-client-golang/CVE-2022-21698
    - debian_importer_v2/golang-github-prometheus-client-golang/CVE-2022-21698
    - debian_importer_v2/golang-github-prometheus-client-golang/CVE-2022-21698
  fixing_advisories: []
