- purl: pkg:rpm/redhat/grafana@9.2.10-24.el9_4?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23746
- purl: pkg:rpm/redhat/grafana@9.2.10-24.el9_4?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23746
- purl: pkg:rpm/redhat/grafana@9.2.10-24.el9_4?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23746
- purl: pkg:rpm/redhat/grafana@9.2.10-24.el9_4?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23746
- purl: pkg:rpm/redhat/grafana@9.2.10-24.el9_4?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:23746
