- purl: pkg:deb/debian/ansible@12.0.0%2Bdfsg-0%2Bdeb13u1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/ansible/CVE-2013-2233
    - debian_importer_v2/ansible/CVE-2013-4259
    - debian_importer_v2/ansible/CVE-2013-4260
    - debian_importer_v2/ansible/CVE-2014-2686
    - debian_importer_v2/ansible/CVE-2014-3498
    - debian_importer_v2/ansible/CVE-2014-4657
    - debian_importer_v2/ansible/CVE-2014-4658
    - debian_importer_v2/ansible/CVE-2014-4659
    - debian_importer_v2/ansible/CVE-2014-4660
    - debian_importer_v2/ansible/CVE-2014-4678
    - debian_importer_v2/ansible/CVE-2014-4966
    - debian_importer_v2/ansible/CVE-2014-4967
    - debian_importer_v2/ansible/CVE-2015-3908
    - debian_importer_v2/ansible/CVE-2015-6240
    - debian_importer_v2/ansible/CVE-2016-3096
    - debian_importer_v2/ansible/CVE-2016-8614
    - debian_importer_v2/ansible/CVE-2016-8628
    - debian_importer_v2/ansible/CVE-2016-8647
    - debian_importer_v2/ansible/CVE-2016-9587
    - debian_importer_v2/ansible/CVE-2017-7466
    - debian_importer_v2/ansible/CVE-2017-7481
    - debian_importer_v2/ansible/CVE-2017-7550
    - debian_importer_v2/ansible/CVE-2018-10855
    - debian_importer_v2/ansible/CVE-2018-10874
    - debian_importer_v2/ansible/CVE-2018-10875
    - debian_importer_v2/ansible/CVE-2018-16837
    - debian_importer_v2/ansible/CVE-2018-16859
    - debian_importer_v2/ansible/CVE-2018-16876
    - debian_importer_v2/ansible/CVE-2019-10156
    - debian_importer_v2/ansible/CVE-2019-10206
    - debian_importer_v2/ansible/CVE-2019-10217
    - debian_importer_v2/ansible/CVE-2019-14846
    - debian_importer_v2/ansible/CVE-2019-14856
    - debian_importer_v2/ansible/CVE-2019-14858
    - debian_importer_v2/ansible/CVE-2019-14864
    - debian_importer_v2/ansible/CVE-2019-14904
    - debian_importer_v2/ansible/CVE-2019-14905
    - debian_importer_v2/ansible/CVE-2019-3828
    - debian_importer_v2/ansible/CVE-2020-10684
    - debian_importer_v2/ansible/CVE-2020-10685
    - debian_importer_v2/ansible/CVE-2020-10691
    - debian_importer_v2/ansible/CVE-2020-10729
    - debian_importer_v2/ansible/CVE-2020-10744
    - debian_importer_v2/ansible/CVE-2020-14330
    - debian_importer_v2/ansible/CVE-2020-14332
    - debian_importer_v2/ansible/CVE-2020-14365
    - debian_importer_v2/ansible/CVE-2020-1733
    - debian_importer_v2/ansible/CVE-2020-1735
    - debian_importer_v2/ansible/CVE-2020-1737
    - debian_importer_v2/ansible/CVE-2020-1739
    - debian_importer_v2/ansible/CVE-2020-1740
    - debian_importer_v2/ansible/CVE-2020-1746
    - debian_importer_v2/ansible/CVE-2020-1753
    - debian_importer_v2/ansible/CVE-2020-25635
    - debian_importer_v2/ansible/CVE-2020-25636
    - debian_importer_v2/ansible/CVE-2020-25646
    - debian_importer_v2/ansible/CVE-2021-20178
    - debian_importer_v2/ansible/CVE-2021-20180
    - debian_importer_v2/ansible/CVE-2021-20191
    - debian_importer_v2/ansible/CVE-2021-20228
    - debian_importer_v2/ansible/CVE-2021-3447
    - debian_importer_v2/ansible/CVE-2021-3583
    - debian_importer_v2/ansible/CVE-2021-3620
    - debian_importer_v2/ansible/CVE-2022-3697
    - debian_importer_v2/ansible/CVE-2023-4237
    - debian_importer_v2/ansible/CVE-2023-5115
    - debian_importer_v2/ansible/CVE-2023-5764
    - debian_importer_v2/ansible/CVE-2024-0690
    - debian_importer_v2/ansible/CVE-2024-11079
    - debian_importer_v2/ansible/CVE-2024-8775
    - debian_importer_v2/ansible/CVE-2024-9902
    - debian_importer_v2/ansible/CVE-2025-14010
