- purl: pkg:rpm/redhat/grafana@7.3.6-4.el8_4?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0002
- purl: pkg:rpm/redhat/grafana@7.3.6-4.el8_4?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0002
- purl: pkg:rpm/redhat/grafana@7.3.6-4.el8_4?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0002
- purl: pkg:rpm/redhat/grafana@7.3.6-4.el8_4?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0002
- purl: pkg:rpm/redhat/grafana@7.3.6-4.el8_4?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0002
