- purl: pkg:deb/debian/golang-github-prometheus-exporter-toolkit@0.15.0-1?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/golang-github-prometheus-exporter-toolkit/CVE-2022-46146
