- purl: pkg:rpm/redhat/cloud-init@22.1-8.el8_8.2?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11339
- purl: pkg:rpm/redhat/cloud-init@22.1-8.el8_8.2?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2025:11339
