- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-3.gitceca8c1.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2769
    - redhat_importer_v2/RHSA-2019:3265
    - redhat_importer_v2/RHSA-2019:3906
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-3.gitceca8c1.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:2769
    - redhat_importer_v2/RHSA-2019:3265
    - redhat_importer_v2/RHSA-2019:3906
- purl: pkg:rpm/redhat/golang-github-openshift-prometheus-alert-buffer@0-3.gitceca8c1.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2019:3906
