- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.404-1.git.1062.611825d.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0833
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.404-1.git.1062.611825d.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2021:0833
