- purl: pkg:deb/debian/prometheus@2.53.3%2Bds1-2?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/prometheus/CVE-2019-3826
    - debian_importer_v2/prometheus/CVE-2021-29622
