- purl: pkg:rpm/redhat/docker@1.3.2-4.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2014:1977
- purl: pkg:rpm/redhat/docker@1.3.2-4.el7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2014:1977
