- purl: pkg:rpm/redhat/grafana@9.2.10-16.el8_10?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:3265
- purl: pkg:rpm/redhat/grafana@9.2.10-16.el8_10?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:3265
- purl: pkg:rpm/redhat/grafana@9.2.10-16.el8_10?arch=s390x
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:3265
- purl: pkg:rpm/redhat/grafana@9.2.10-16.el8_10?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:3265
- purl: pkg:rpm/redhat/grafana@9.2.10-16.el8_10?arch=aarch64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2024:3265
