- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=x86&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=x86_64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=aarch64&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=armhf&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=armv7&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=ppc64le&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
- purl: pkg:apk/alpine/grafana@8.5.9-r0?arch=s390x&distroversion=v3.16&reponame=community
  affected_by_advisories: []
  fixing_advisories:
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31097
    - alpine_linux_importer_v2/grafana/v3.16/8.5.9-r0/CVE-2022-31107
