- purl: pkg:rpm/redhat/ansible@2.9.23-1.el8ap?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:2703
- purl: pkg:rpm/redhat/ansible@2.9.23-1.el8ap?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2021:2703
