- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-9.el8_7?arch=src
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:9058
- purl: pkg:rpm/redhat/prometheus-jmx-exporter@0.12.0-9.el8_7?arch=noarch
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:9058
