- purl: pkg:deb/debian/cloud-init@19.4-2?distro=trixie
  affected_by_advisories: []
  fixing_advisories:
    - debian_importer_v2/cloud-init/CVE-2020-8631
    - debian_importer_v2/cloud-init/CVE-2020-8632
