- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.634-1.g609cd20.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0555
- purl: pkg:rpm/redhat/prometheus-node-exporter@3.11.634-1.g609cd20.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:0555
