- purl: pkg:rpm/redhat/prometheus@3.11.51-1.git.5023.0ad933c.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3743
- purl: pkg:rpm/redhat/prometheus@3.11.51-1.git.5023.0ad933c.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2018:3743
