- purl: pkg:deb/ubuntu/prometheus-alertmanager@0.23.0-4ubuntu0.2?arch=source&distro=esm-apps/jammy
  affected_by_advisories:
    - ubuntu_osv_importer_v2/UBUNTU-CVE-2023-40577
  fixing_advisories: []
