- purl: pkg:rpm/redhat/prometheus-promu@0.5.0-2.git642a960.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHBA-2020:0063
    - redhat_importer_v2/RHSA-2019:3245
