- purl: pkg:rpm/redhat/prometheus@3.11.685-1.g99aae51.el7?arch=x86_64
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:1420
- purl: pkg:rpm/redhat/prometheus@3.11.685-1.g99aae51.el7?arch=ppc64le
  affected_by_advisories: []
  fixing_advisories:
    - redhat_importer_v2/RHSA-2022:1420
